default:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://10.1.218.157/multi_tenant_base?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  dbUsername: root
  dbPassword:
  tenantDataSourceTable: acl_tenant_datasource