apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-endpoint
subsets:
  - addresses:
      - ip: 192.168.2.102
    ports:
      - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-endpoint
spec:
  clusterIP: 10.1.218.157
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multi-tenant-deployment
spec:
  revisionHistoryLimit: 10
  replicas: 2
  template:
    metadata:
      labels:
        app: multi-tenant
    spec:
      containers:
        - name: multi-tenant
          image: 192.168.2.200:5000/multi-tenant:latest
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: multi-tenant-service
spec:
  type: NodePort
  selector:
    app: multi-tenant
  ports:
    - port: 7081
      protocol: TCP
      targetPort: 7081
      nodePort: 30081

