apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-endpoint
subsets:
  - addresses:
      - ip: 192.168.2.102
    ports:
      - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-endpoint
spec:
  clusterIP: 10.1.218.157
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multi-tenant-deployment
spec:
  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        app: multi-tenant
    spec:
      containers:
        - name: multi-tenant
          image: 192.168.2.200:5000/multi-tenant:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 7081
              path: /multi-tenant/ping
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 7081
              path: /multi-tenant/ping
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: multi-tenant-service
spec:
  type: NodePort
  selector:
    app: multi-tenant
  ports:
    - port: 7081
      protocol: TCP
      targetPort: 7081
      nodePort: 30081

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080  #http
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 30443  #https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: multi-tenant-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: k8s.walter.com
      http:
        paths:
          - path: /multi-tenant
            backend:
              serviceName: multi-tenant-service
              servicePort: 7081
